# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Default'

variables:
  ANSIBLE_HOST_KEY_CHECKING: 'False'  # Optional, disables SSH prompt

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install ansible
    displayName: 'Install Ansible'

  - checkout: self
  - task: DownloadSecureFile@1
    name: sshKey
    inputs:
       secureFile: id_rsa

  - script: |
      mkdir -p ~/.ssh
      cp $(sshKey.secureFilePath) ~/.ssh/id_rsa
      echo $(sshKey.secureFilePath)
      chmod 600 ~/.ssh/id_rsa
      echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
    displayName: 'Set up SSH Key'  
  

  - script: |
      ansible --version
      ansible-playbook -i inventory.ini playbook.yaml
    displayName: 'Run Ansible Playbook'

